### PR TITLE
examples: add Android soft input keyboard example

### PR DESCRIPTION
**Pull request by Larpon**
Please note that it currently depends on https://github.com/Larpon/jni to be installed in `~/.vmodules`

### CODE REVIEW

**Comment by xandro0777** [comment]
Hi,

>   https://github.com/vlang/ui/pull/385

thanks for this code, however In am confused - where did this code go?
I can't see it when I check out vlang/ui ?

 
> https://github.com/vlang/ui/pull/385.patch
> https://github.com/vlang/ui/pull/385.diff

**Comment by Larpon** [comment]
> Hi,
> #385
> thanks for this code, however In am confused - where did this code go? I can't see it when I check out vlang/ui ?
> […](#)
> https://github.com/vlang/ui/pull/385.patch https://github.com/vlang/ui/pull/385.diff

It's in my branch `feature/android-keyboard-example` in the `examples/textbox_input` directory:
https://github.com/Larpon/ui/tree/feature/android-keyboard-example/examples/textbox_input

**Comment by xandro0777** [comment]
On Mon, 06 Sep 2021 01:09:50 -0700
Larpon ***@***.***> wrote:


> It's in my branch `feature/android-keyboard-example` in the
> `examples/textbox_input` directory:
> https://github.com/Larpon/ui/tree/feature/android-keyboard-example/examples/textbox_input

I am playing with the example and when trying to adapt it to work with
multiple textbox fields I have the problem that on_soft_input doesn't
appear to know into which textbox the input belongs.

Do I have to query which textbox has focus or am I overlooking some
more elegant solution?
>

**Comment by Larpon** [comment]
You need to adapt on_soft_input in such a way that it send and receive from the correct text input. If you have multiple inputs you'll have to control the state of each manually. I wasn't able to intercept clicks on the textbox but if this is fixed or available then it should be pretty trivial

**Comment by xandro0777** [comment]
On Sun, 19 Sep 2021 07:02:47 -0700
Larpon ***@***.***> wrote:

> You need to adapt on_soft_input in such a way that it send and
> receive from the correct text input. If you have multiple inputs
> you'll have to control the state of each manually. I wasn't able to
> intercept clicks on the textbox but if this is fixed or available
> then it should be pretty trivial

I think that intercepting clicks won't do it reliably, user may press
tab or the focus may change programatically. It should be possible to
test textbox.is_focused but won't scale great.

I was looking at ui_widget_focusable.v but it doesn't appear to provide
a way to query what is focused - maybe this should be added as this
would provide an elegant and simple way to solve this?

**Comment by xandro0777** [comment]
On Sun, 19 Sep 2021 07:02:47 -0700
Larpon ***@***.***> wrote:

Looking more into it I think that window_key_down() and/or
window_char() should be called which would propagate the key to the
respective handlers in textbox.v
Do you think that would work?

In addition to this I believe the generic ui could use some
enhancement in focus handling. If a textbox is focused an on_focus
method should be called which would make the soft keyboard visible -
and for example display only a numeric keypad if the textbox is a
numeric one. Right know if I hide the keyboard in hte example app I
don't see how to reenable it again.

**Comment by xandro0777** [comment]
On Tue, 21 Sep 2021 22:08:19 +0200
***@***.***> wrote:

Oh well, naively tried

```
	       e := ui.KeyEvent{
			// key: ui.Key(char_code) // Key(event.key_code)
			mods: ui.KeyMod(0) // KeyMod(event.modifiers)
			codepoint: char_code
			// code: int(char_code)
			// action: action
			// mods: mod
		}
		// app.window.eventbus.publish(ui.events.on_key_down, app.window, e)

		app.window.eventbus.publish(ui.events.on_char,
		app.window, e)
```

which didn't work. Don't have the time to debug that now.

**Comment by xandro0777** [comment]
On Sun, 19 Sep 2021 07:02:47 -0700
Larpon ***@***.***> wrote:

I have now figured out how to generate "synthetic" key presses and
applied it to the Android example although I have just regular keys
for now, no tab/del/enter yet.

There still remains the problem that focus control is not working on
android apparently.

**Comment by xandro0777** [comment]
On Sun, 19 Sep 2021 07:02:47 -0700
Larpon ***@***.***> wrote:


Figured out why focusing textboxes was broken on android, pretty trivial
detail:

https://github.com/vlang/ui/issues/389

**Comment by Larpon** [comment]
> On Sun, 19 Sep 2021 07:02:47 -0700 Larpon ***@***.***> wrote: Figured out why focusing textboxes was broken on android, pretty trivial detail: #389

I'm glad you figured it out in the end :slightly_smiling_face: :+1:

**Comment by xandro0777** [comment]
On Mon, 04 Oct 2021 00:59:18 -0700
Larpon ***@***.***> wrote:

> > On Sun, 19 Sep 2021 07:02:47 -0700 Larpon ***@***.***> wrote:
> > Figured out why focusing textboxes was broken on android, pretty
> > trivial detail: #389  
> 
> I'm glad you figured it out in the end :slightly_smiling_face: :+1: 
> 

I have submitted https://github.com/vlang/ui/pull/395 , the change is
trivial but my experience with github close to zero. Please have a look.

**Pull request merged**
