### PR TITLE
better stack management and alignment

### PR DESCRIPTION
**Pull request by rcqls**
This PR mainly does:

* better management of size and position (Still it is a work in progress)
* better alignment

Also, it introduces for Stack:

* In StackConfig (only not in Stack), width and height  is now f32 offering relative width from parent (see example users.v) when value is between 0 and 1 (percentage of the parent)
* for stack vertical_alignments and horizontal_alignments allow us to align children differently (see users.v)

### CODE REVIEW

**Comment by medvednikov** [comment]
needs a minor update

```
 error: type `ui.MarginConfig` is private
   24 |             spacing: 20
   25 |             margin: {
   26 |                 top: 30
      |                 ~~~~~~~
   27 |                 left: 30
   28 |                 right: 30
slider.v:44:15: error: type `ui.MarginConfig` is private
   42 |             stretch: true
   43 |             alignment: .center
   44 |             margin: ui.MarginConfig{5, 5, 5, 5}
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~
   45 |             spacing: 10
   46 |         }, [```

**Comment by rcqls** [comment]
> needs a minor update
> 
> ```
>  error: type `ui.MarginConfig` is private
>    24 |             spacing: 20
>    25 |             margin: {
>    26 |                 top: 30
>       |                 ~~~~~~~
>    27 |                 left: 30
>    28 |                 right: 30
> slider.v:44:15: error: type `ui.MarginConfig` is private
>    42 |             stretch: true
>    43 |             alignment: .center
>    44 |             margin: ui.MarginConfig{5, 5, 5, 5}
>       |                        ~~~~~~~~~~~~~~~~~~~~~~~~
>    45 |             spacing: 10
>    46 |         }, [```
> ```

thanks it is fixed now!

**Comment by rcqls** [comment]
@medvednikov I guess that the v fmt failure test is related to different version of v?

**Comment by medvednikov** [comment]
Thank you.

**Pull request merged**
