### PR TITLE
ci: add regression tests via `v gret`

### PR DESCRIPTION
**Pull request by Larpon**

### CODE REVIEW

**Comment by xandro0777** [comment]
ROFL. I knew github is noisy but this is beyond ridiculous.

Wondering whether the issue number (404) triggers some funny bug in some tool thinking it is hitting a HTTP 404 and retrying forever?

**Comment by Larpon** [comment]
@xandro0777 Sorry, I didn't know it would take that many retries :)
I will try to close the testing ASAP - and do it on a fork the next time :grimacing:

**Comment by Larpon** [comment]
Ready :+1: sorry for the noise :)

**Comment by xandro0777** [comment]
>Ready :+1: sorry for the noise :)

no problem, I was just worried that some tool ran amuck.

**Pull request merged**
