### PR TITLE
Rectangle

### PR DESCRIPTION
**Pull request by memeone**
```v
ui.rectangle({
  height int
  width  int
  color  gx.Color
  radius int = 0
  border bool = false
  border_color gx.Color = gx.Color { r: 180, g: 180, b: 190 }
  ref   &Rectangle
})
```
preview

### CODE REVIEW

**Comment by memeone** [comment]
Depends on https://github.com/vlang/v/pull/3616

**Comment by medvednikov** [comment]
Hm I think this should be drawn in Canvas, not be a separate widget.

**Comment by memeone** [comment]
In my opinion rectangles are general enough to be useful as a standard widget. They can be used in lots of places for indicators etc. Also, it’s very annoying to manually deal with layout

**Comment by adlesh** [comment]
I agree w/ @memeone . vui should have a few of the most common items readily available and only require canvas drawing if you want to something more advanced. Feels like that goes better w/ v overall

**Comment by memeone** [comment]
Maybe this should be renamed though as it is also a circle if you set radius to width/2

**Pull request merged**
