### PR TITLE
open_url: windows implementation

### PR DESCRIPTION
**Pull request by serkonda7**
Tested in cmd and powershell.

### CODE REVIEW

**Comment by changrui** [comment]
`cmd /c start url` uner Windows.

**Comment by serkonda7** [comment]
For what is the cmd /c part?

**Comment by serkonda7** [comment]
@changrui what is the `cmd /c` part required for?

**Comment by Delta456** [comment]
> cmd /c start url

This is only for cmd. Just doing `start url` works everywhere.

**Pull request merged**
