### PR TITLE
Justification of text in label widget,  grid work, improvement on scrollview, style redesign

### PR DESCRIPTION
**Pull request by rcqls**
* justification of text label
* improvement of scrollview (no more reinit when resizing)
* grid current position

### CODE REVIEW

**Comment by medvednikov** [comment]
There's a UI regression, and the upload to imgur failed.

Can you please have a look @Larpon?

**Comment by rcqls** [comment]
>

**Comment by rcqls** [comment]
@medvednikov @Larpon No need for now to regenerate the graphical regression images since I need to deactivate temporarily the graphical regression when developing style. The PR can be then merged.

**Comment by Larpon** [comment]
The images from imgur is deleted already so that'll be hard right now. I can see why they need to be disabled while you're working on it. @rcqls are you working on *all* of them - or only some? We can disable them more fine grained if need be.

**Comment by rcqls** [comment]
> The images from imgur is deleted already so that'll be hard right now. image I can see why they need to be disabled while you're working on it. @rcqls are you working on _all_ of them - or only some? We can disable them more fine grained if need be.

At some point, I need to think about it. But for sure right now and for a little while when working on styling I think it is better to deactivate the test because it can change the look and feel pretty often. Also I'll try to prepare some more dedicated v ui tests.

**Pull request merged**
