### PR TITLE
add switch

### PR DESCRIPTION
**Pull request by origel**
add switch control

use this command to see:
v run examples/switch.v

### CODE REVIEW

**Comment by Delta456** [comment]
Can you also attach a screenshot? Thanks

**Comment by origel** [comment]
screenshots are attached

**Comment by medvednikov** [comment]
Thanks!

So this is like a fancy version of a checkbox, right? With more focus on mobile.

**Comment by memeone** [comment]
I think it's a good adition, switches feel more fitting for settings than checkboxes. And checkboxes feel better than switches for forms etc (my opinion)

**Comment by origel** [comment]
Yes, it's This is another option for checkbox and fit for mobile.

**Pull request merged**
