### PR TITLE
Slider widget update

### PR DESCRIPTION
**Pull request by progamateur**
- slider widget fixes and add/changes, refer to slider.v update comments
- update rectangle widget
- window.v fix to get correct mouse position on mouse movement
- examples : fix slider.v 
                    add slider_textbox.v  example
                    add rgb_color.v example

### CODE REVIEW

**Comment by progamateur** [comment]
for windows, no build issue of all examples in  .vmodules/ui/examples :
os : windows 10 (1909)
C compiler : gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
V version : V 0.1.25 050ec5d

**Comment by medvednikov** [comment]
Yes, 0.1.25 has to be used for now.

Can you run `v fmt -w` please?

**Comment by progamateur** [comment]
. Format source files:
   - slider.v
   - window.v
   - examples/slider.v
   - examples/slider_textbox.v

**Comment by medvednikov** [comment]
lovely!
Screenshot 2020-04-15 at 02 13 07

**Pull request merged**
