### PR TITLE
fix compilation

### PR DESCRIPTION
**Pull request by Delta456**
From https://github.com/vlang/v/runs/1672980542

### CODE REVIEW

**Comment by spaceface777** [comment]
Doesn't #272 already fix this as well?

**Comment by Delta456** [comment]
I didn't see that one but I believe casting here is better than introducing a new `enum` for this.

**Comment by spytheman** [comment]
It does, #272 has other changes too that will be useful in the future.

**Comment by spytheman** [comment]
The casting here is a more targeted change, in the sense that it does just what is enough to fix the compilation for now.

#272 also makes it easier for future users of ui - using enum names is more readable and is checked by the compiler, so I think it will improve usability.

**Comment by Delta456** [comment]
True so I will close this.

**Pull request closed without merging**
