### PR TITLE
handle touch events in textbox.v

### PR DESCRIPTION
**Pull request by xandro0777**
should react to touch_down/up so that editing and focus work on touch screens. On Android some more additions will be required but lets start small.

### CODE REVIEW

**Comment by xandro0777** [comment]
Puzzled about the build failures - is that something that this PR caused? Can't see how.

**Comment by xandro0777** [comment]
There should be ```int height``` in https://github.com/vlang/v/blob/master/thirdparty/sokol/sokol_app.h#L3035 but still puzzled why this code is hit on Ubuntu/Windows?

**Comment by Larpon** [comment]
It's likely something to do with [this commit](https://github.com/vlang/v/commit/d8ea9e4969b699c2514316e56a55770084eddf09) - I'm not sure if it actually fixes this or caused this.
@medvednikov why the move of `_sapp_macos_resize_window`? :slightly_smiling_face: - if you fixed something can you please re-run CI here :smile:

**Comment by medvednikov** [comment]
@Larpon re-run worked :)

**Pull request merged**
