### PR TITLE
debug refactor

### PR DESCRIPTION
**Pull request by kahsa**
In `ui_extra_debug.v`, there are methods for `Stack` and `Widget`, but if you use these structs as receivers in this file, you will get a compilation error if the Stack file and this file are not in the same module.
On the other hand, if you move the receiver as an argument, you can just import the Stack.
In this way, it is loosely coupled and allows for more flexibility in module differentiation.

Consequently, the function names have also been adjusted.

Added `examples/simple.v` for temporal quick check.

### CODE REVIEW

**Comment by spytheman** [comment]
I do not understand the problem that this solves.
Can you add an example that does not compile at master, but does with your PR?

**Comment by spytheman** [comment]
This compiles on both master, and in your PR, so it is not a good example imho:
```v
import ui

fn main() {
        lbl := ui.label(text: 'Label')
        window := ui.window(
                width: 300
                height: 200
                children: [ui.row(children: [lbl])]
        )
        ui.run(window)
}
```

**Comment by kahsa** [comment]
In conclusion, this is the kind of error I get.
```
/home/tsukasa/.vmodules/ui/debug/ui_extra_debug.v:7:7: error: cannot define new methods on non-local type ui.Stack
    5 | 
    6 | // Draw bounding box for Stack
    7 | fn (s &ui.Stack) draw_bb() {
      |       ~~~~~~~~~
    8 |     mut col := gx.red
    9 |     if s.direction == .row {
```

**Comment by kahsa** [comment]
> This compiles on both master, and in your PR, so it is not a good example imho:
> 
> ```v
> import ui
> 
> fn main() {
>         lbl := ui.label(text: 'Label')
>         window := ui.window(
>                 width: 300
>                 height: 200
>                 children: [ui.row(children: [lbl])]
>         )
>         ui.run(window)
> }
> ```

That sample is not absolutely necessary for this PR.
I used it because I didn't have a small, minimal, usable sample.
I thought about deleting it before I did the PR, but I thought it would be a good sample of how `ui` works even if it is minimal and doesn't use Layout, so I didn't delete it.
It's not absolutely necessary, so should I delete it?

**Comment by spytheman** [comment]
For some reason, this could not be merged through the web UI.
I merged it through following the instructions from here:
image

This is the second time, that it happens with one of your PRs @kahsa, can you please check the settings of your github repository, and/or delete it, then fork https://github.com/vlang/ui again?

**Pull request closed without merging**
